spring:
  datasource:
    username: MYJAVA
    password: 1234
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
    driver-class-name: oracle.jdbc.OracleDriver
  #禁用模板引擎缓存
  groovy:
    template:
      cache: false

logging:
  level:
    root: info
#    showsql
    com:
      anzaiyun:
        mapper: debug

server:
  port: 8088

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.anzaiyun.dao